[package]
name = "counts"
version = "0.2.0"
authors = ["Nicholas Nethercote <n.nethercote@gmail.com>"]
license = "Unlicense"
description = "A command line tool for ad hoc profiling."
readme = "README.md"
homepage = "https://github.com/nnethercote/counts"
repository = "https://github.com/nnethercote/counts"
keywords = ["cli", "profiling"]
categories = ["command-line-utilities", "development-tools::profiling"]
edition = "2021"

[dependencies]
regex = "1.0"
fxhash = "0.2"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1.0"
tempfile = "3.0"

# These options make the binary a bit smaller.
[profile.release]
panic = "abort"
lto = true
