[package]
name = "counts"
version = "0.1.2"
authors = ["Nicholas Nethercote <n.nethercote@gmail.com>"]
license = "Unlicense"
description = "A command line tool for ad hoc profiling."
readme = "README.md"
homepage = "https://github.com/nnethercote/counts"
repository = "https://github.com/nnethercote/counts"
keywords = ["cli", "profiling"]
categories = ["command-line-utilities", "development-tools::profiling"]
edition = "2018"

[dependencies]
regex = "1.0"
fxhash = "0.2"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3"
