[package]
name = "counts"
version = "0.1.0"
authors = ["Nicholas Nethercote <nnethercote@mozilla.com>"]

[dependencies]
fnv = "1.0"
regex = "1.0"

# Used for profiling
#[profile.release]
#debug = true
